### ISSUE TITLE
Crashed on Ulauncher

### ISSUE THREAD

**Issue by vardhin** [tuanpham-dev/ulauncher-better-calculator#4]
-> Ways to reproduce issue:
     Install extension in Ulauncher
![image](https://github.com/tuanpham-dev/ulauncher-better-calculator/assets/115967495/8c376fdc-2cb6-4ba8-acae-087794976e6e)

additional info:
    budgie desktop env, arch linux (btw)

**Comment by Exordio** [comment]
Same problem. 
```
2024-06-02 18:43:49,274 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tuan
pham-dev.ulauncher-better-calculator" started. PID 1926
2024-06-02 18:43:49,283 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tua
npham-dev.ulauncher-better-calculator" was terminated with code 1
```

Arch linux, python 3.12.3

**Comment by Exordio** [comment]
more info:

```
Traceback (most recent call last):
  File "/home/exord/.local/share/ulauncher/extensions/com.github.tuanpham-dev.ulauncher-better-calculator/main.py", line 2, in <module>
    from py_expression_eval import Parser
ModuleNotFoundError: No module named 'py_expression_eval'
2024-06-02 20:57:25,102 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tuanpham-dev.ulauncher-better-calculator" was terminated with code 1

```

**Comment by Exordio** [comment]
@vardhin Hi, I fixed it by installing this library on the system python pkgs. Try doing this, i think it will probably work for you too.

1. This is so that it is possible to install pip packages into the system. It may be a little unsafe, so as an option you can simply rename this file instead of deleting it.
```
sudo rm /usr/lib/python3.12/EXTERNALLY-MANAGED
```

2. install missing lib

```
python -m pip install -U py_expression_eval
```

3. If you deleted it, I recommend returning it for safety. There's no special content there. When you run pip, it simply checks for its presence.

```
echo -e "# This environment is externally managed\n# Please refer to your system package manager for updates or installation of new packages." | sudo tee /usr/lib/python3.12/EXTERNALLY-MANAGED
```

And also check your version of python, I have 3.12 on my system, so the path was written exactly like this.

=======

If the error does not go away. Look at the problems when u launch ulauncher.  do something like this:

```
ulauncher --dev -v
```

And then look for the log section where the add-on was initialized

**Comment by vardhin** [comment]
Thanks buddy
